services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USER: username
      DB_PASSWORD: password
      DB_NAME: username
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: username
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
