services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USER: postgres
      DB_PASSWORD: Prague1993
      DB_NAME: postgres
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Prague1993
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
