version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: -
      POSTGRES_PASSWORD: -
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://-:-@db:5432/mydb
    ports:
      - "8080:8080"

volumes:
  pgdata:
