basePath: /
definitions:
  main.Camera:
    properties:
      id:
        type: string
      latitude:
        type: number
      longitude:
        type: number
      name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is the Backend Service API for handling MTG cards and Cameras.
  title: Backend Service Assignment API
  version: "1.0"
paths:
  /cameras:
    get:
      consumes:
      - application/json
      description: List cameras within a specified radius of a given location
      parameters:
      - description: Latitude
        in: query
        name: latitude
        required: true
        type: number
      - description: Longitude
        in: query
        name: longitude
        required: true
        type: number
      - description: Radius in meters
        in: query
        name: radius
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/main.Camera'
            type: array
        "400":
          description: Invalid parameters
          schema:
            type: string
      summary: List cameras by radius
      tags:
      - cameras
  /cameras/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve a specific camera by its ID
      parameters:
      - description: Camera ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Camera'
        "404":
          description: Camera not found
          schema:
            type: string
      summary: Get camera by ID
      tags:
      - cameras
  /health:
    get:
      description: Check if the server is running
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Health Check
      tags:
      - health
schemes:
- http
swagger: "2.0"
