resilience4j:
  circuitbreaker:
    instances:
      orderService:
        register-health-indicator: true
  retry:
    instances:
      orderService:
        max-retry-attempts: 3

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

opentelemetry:
  instrumentation:
    methods:
      com.example.service.*: true
